root: true
env:
  node: true
  browser: true
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  prettier/prettier: error
  no-unused-vars:
    - error
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  no-console:
    - off
  no-var:
    - error
  prefer-const:
    - error
  prefer-rest-params:
    - warn
  prefer-spread:
    - warn
  prefer-template:
    - warn
  camelcase:
    - warn
